### ISSUE TITLE
target process being ignored

### ISSUE THREAD

**Issue by jonnymangothinkjam** [loksland/jsxk#1]
Hey I'm trying to target photoshop with a JSX script, 

using the example and running it, for some reason, opens after effects instead.

I've tried 
```
const jsxk = require('jsxk');

// tried with and without this line
jsxk.options.targetProcess = 'Adobe Photoshop CC 2018';
jsxk.exec('roomNamesReplacer.jsx').then(console.log,console.error);
```

JSX:
```
#target photoshop

app.bringToFront();

jsxOnComplete({msg:'Hi from JSX'});

function jsxOnComplete(data){
// Will be overridden
}


```
any ideas?

Thanks!

**Comment by loksland** [comment]
Thanks for flagging this, it was a bug. Check out the latest version (0.1.8) for the fix.

**Comment by jonnymangothinkjam** [comment]
it works - thank you for the quick fix!
